Classroom.create("name"=>"Main")
Course.create("name"=>"English 101", "classroom_id"=>1)
Course.create("name"=>"Math 101", "classroom_id"=>1)
Course.create("name"=>"Science 101", "classroom_id"=>1)
Teacher.create("user_name"=>"larryteacher", "password_digest"=>"asdfasdfasdfsadf", "first_name"=>"Larry", "last_name"=>"Teacher", "email"=>"larry@email.com")
Student.create("user_name"=>"joestudent", "password_digest"=>"asdfasdfasdfsadf", "first_name"=>"Joe", "last_name"=>"Student", "email"=>"joe@email.com")
Topic.create("course_id"=>1, "title"=>"Grammar")
