Course.create({"id"=>1, "name"=>"English 101", "code"=>"1111", "featured"=>true, "short_desc"=>"Learn the basics.", "long_desc"=>"Shields up. I recommend we transfer power to phasers and arm the photon torpedoes. Something strange on the detector circuit. The weapons must have disrupted our communicators. You saw something as tasty as meat, but inorganically materialized out of patterns used by our transporters. Captain, the most elementary and valuable statement in science, the beginning of wisdom, is 'I do not know.' All transporters off."})
Course.create({"id"=>2, "name"=>"Math 101", "code"=>"2222", "featured"=>false, "short_desc"=>"Build fundamentals.", "long_desc"=>"Unidentified vessel travelling at sub warp speed, bearing 235.7. Fluctuations in energy readings from it, Captain. All transporters off. A strange set-up, but I'd say the graviton generator is depolarized. The dark colourings of the scrapes are the leavings of natural rubber, a type of non-conductive sole used by researchers experimenting with electricity. The molecules must have been partly de-phased by the anyon beam."})
Course.create({"id"=>3, "name"=>"Science 101", "code"=>"3333", "featured"=>false, "short_desc"=>"Why ask why?", "long_desc"=>"Now what are the possibilities of warp drive? Cmdr Riker's nervous system has been invaded by an unknown microorganism. The organisms fuse to the nerve, intertwining at the molecular level. That's why the transporter's biofilters couldn't extract it. The vertex waves show a K-complex corresponding to an REM state. The engineering section's critical. Destruction is imminent. Their robes contain ultritium, highly explosive, virtually undetectable by your transporter."})
Course.create({"id"=>4, "name"=>"Art 101", "code"=>"4444", "featured"=>true, "short_desc"=>"Grab your paintbrush.", "long_desc"=>"Run a manual sweep of anomalous airborne or electromagnetic readings. Radiation levels in our atmosphere have increased by 3,000 percent. Electromagnetic and subspace wave fronts approaching synchronization. What is the strength of the ship's deflector shields at maximum output? The wormhole's size and short period would make this a local phenomenon. Do you have sufficient data to compile a holographic simulation?"})

Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.1_mok0nw.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.2_e4qfq4.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.3_zr6flp.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.4_xkfi4s.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.5_fb01ug.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.6_mw8w5y.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.7_lbrzns.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.8_ujdsd6.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.9_qkkmzd.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.10_xpq8jt.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.11_vogdod.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.12_z5ttt9.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.13_rfhnph.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.14_cmkiao.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.15_lfyyhg.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.16_u1yyzl.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.17_dkhfcf.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.18_p56g9e.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.19_ywbn3n.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.20_lddaev.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.21_vwuhla.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.22_refrws.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.23_be7asr.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.24_q5chbm.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.25_lenvpf.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.26_wghard.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.27_mo9jad.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.28_oykcbg.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.29_xs2xwy.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.30_tbwvql.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.31_tetcji.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.32_vrxsbk.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.33_hzxkea.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.34_yiprz1.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.35_ifsdsl.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.36_se9bx8.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.37_honylz.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.38_s6cuzj.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.39_mylenx.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.40_h51mgj.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.41_oodzta.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.42_sjlcbp.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.43_k5e4n2.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.44_jcvidg.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.45_jznt80.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.46_cdokqi.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.47_hiz8ct.png")
Avatar.create("url"=>"https://res.cloudinary.com/fergusdev/image/upload/v1589054973/aliens/alien.48_jxct9m.png")

User.create("type"=>"Teacher","avatar_id"=>1,"user_name"=>"LarryTeacher", "password"=>"password", "first_name"=>"Larry", "last_name"=>"Teacher", "email"=>"larry@email.com")
User.create("type"=>"Teacher","avatar_id"=>2,"user_name"=>"MoeTeacher", "password"=>"password", "first_name"=>"Moe", "last_name"=>"Teacher", "email"=>"moe@email.com")
User.create("type"=>"Teacher","avatar_id"=>3,"user_name"=>"CurleyTeacher", "password"=>"password", "first_name"=>"Curley", "last_name"=>"Teacher", "email"=>"curley@email.com")

User.create("type"=>"Student","avatar_id"=>4,"user_name"=>"JimmyStudent", "password"=>"password", "first_name"=>"Jimmy", "last_name"=>"Student", "email"=>"jimmy@email.com")
User.create("type"=>"Student","avatar_id"=>5,"user_name"=>"BillyStudent", "password"=>"password", "first_name"=>"Billy", "last_name"=>"Student", "email"=>"billy@email.com")
User.create("type"=>"Student","avatar_id"=>6,"user_name"=>"KeatonStudent", "password"=>"password", "first_name"=>"Keaton", "last_name"=>"Student", "email"=>"keaton@email.com")

#Teachers
CourseUser.create("user_id"=>1,"course_id"=>1)
CourseUser.create("user_id"=>1,"course_id"=>2)
CourseUser.create("user_id"=>1,"course_id"=>3)
CourseUser.create("user_id"=>1,"course_id"=>4)
CourseUser.create("user_id"=>2,"course_id"=>2)
CourseUser.create("user_id"=>3,"course_id"=>3)

#Students
CourseUser.create("user_id"=>4,"course_id"=>1)
CourseUser.create("user_id"=>5,"course_id"=>1)
CourseUser.create("user_id"=>6,"course_id"=>1)

CourseUser.create("user_id"=>4,"course_id"=>2)
CourseUser.create("user_id"=>5,"course_id"=>2)
CourseUser.create("user_id"=>6,"course_id"=>2)

CourseUser.create("user_id"=>4,"course_id"=>3)
CourseUser.create("user_id"=>5,"course_id"=>3)

Announcement.create({"id" => 1, "course_id" => 1, "user_id" => 1, "type" => "Announcement", "title" => "First English 101 Announcement", "start_date" => "Mon, 27 Apr 2020", "end_date" => "Mon, 27 Apr 2020", "posted_date" => "Mon, 27 Apr 2020", "due_date" => "Mon, 27 Apr 2020", "graded" => true, "points" => 100, "instructions" => "Do it", "created_at" => "Thu, 14 May 2020 16:40:44 UTC +00.00", "updated_at" => "Thu, 14 May 2020 16:53:24 UTC +00.00" })
Announcement.create({"id" => 2, "course_id" => 2, "user_id" => 1, "type" => "Announcement", "title" => "First Math 101 Announcement", "start_date" => "Mon, 27 Apr 2020", "end_date" => "Mon, 27 Apr 2020", "posted_date" => "Mon, 27 Apr 2020", "due_date" => "Mon, 27 Apr 2020", "graded" => true, "points" => 100, "instructions" => "Do it", "created_at" => "Thu, 14 May 2020 16:40:44 UTC +00.00", "updated_at" => "Thu, 14 May 2020 16:53:44 UTC +00.00" })

Assignment.create({"id" => 3, "course_id" => 3, "user_id" => 1, "type" => "Assignment", "title" => "First Science 101 Assignment", "start_date" => "Mon, 27 Apr 2020", "end_date" => "Mon, 27 Apr 2020", "posted_date" => "Mon, 27 Apr 2020", "due_date" => "Mon, 27 Apr 2020", "graded" => true, "points" => 100, "instructions" => "Do it", "created_at" => "Thu, 14 May 2020 16:40:44 UTC +00.00", "updated_at" => "Thu, 14 May 2020 16:54:04 UTC +00.00" })
Assignment.create({"id" => 4, "course_id" => 4, "user_id" => 1, "type" => "Assignment", "title" => "First Art 101 Assignment", "start_date" => "Mon, 27 Apr 2020", "end_date" => "Mon, 27 Apr 2020", "posted_date" => "Mon, 27 Apr 2020", "due_date" => "Mon, 27 Apr 2020", "graded" => true, "points" => 100, "instructions" => "Do it", "created_at" => "Thu, 14 May 2020 16:40:44 UTC +00.00", "updated_at" => "Thu, 14 May 2020 16:54:20 UTC +00.00" })

Response.create("interaction_id"=>1, "title"=>"Response to First Announcement", "user_id"=>4, "content"=>"bla, bla, bla", "score"=>92, "letter_grade"=>"A")
Response.create("interaction_id"=>2, "title"=>"Response to Second Announcement", "user_id"=>5, "content"=>"bla, bla, bla", "score"=>92, "letter_grade"=>"A")

